--CREATE DATABASE SERVICIOS_BANCARIOS
--GO
--USE SERVICIOS_BANCARIOS
GO
CREATE TABLE Pais 
(
	pais_id INT NOT NULL PRIMARY KEY IDENTITY,
	nombre VARCHAR(80) NOT NULL,
)
GO
CREATE TABLE Cliente
(
	cliente_id INT NOT NULL PRIMARY KEY IDENTITY,
	pais_id INT NOT NULL,
	cedula VARCHAR(20) NOT NULL, 
	nombre VARCHAR(80) NOT NULL,
	apellido_Paterno VARCHAR(80) NOT NULL,
	apellido_Materno VARCHAR(80) NULL,
	sexo VARCHAR(1) NOT NULL,
	fecha_Nacimiento DATETIME NOT NULL,
	ingresos DECIMAL NOT NULL,
	direccion  VARCHAR(80) NOT NULL,
	FOREIGN KEY (pais_id) REFERENCES Pais(pais_id)
)
GO
CREATE TABLE Categoria
(
	categoria_id  INT NOT NULL PRIMARY KEY IDENTITY,
	nombre VARCHAR(80) NOT NULL,
)
GO
CREATE TABLE Producto
(
	producto_id INT NOT NULL PRIMARY KEY IDENTITY,
	categoria_id INT NOT NULL,
	codigo VARCHAR(80) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	fecha_registro DATETIME NOT NULL,
	FOREIGN KEY (categoria_id) REFERENCES Categoria(categoria_id)
)
GO
CREATE TABLE CondicionTipo
(
	condicion_tipo_id INT NOT NULL PRIMARY KEY IDENTITY,
	nombre VARCHAR(80) NOT NULL,
)
GO
CREATE TABLE Condicion
(
	condicion_id INT NOT NULL PRIMARY KEY IDENTITY,
	condicion_tipo_id INT NOT NULL,
	producto_id INT NOT NULL,
	valor DECIMAL NOT NULL,
	FOREIGN KEY (condicion_tipo_id) REFERENCES CondicionTipo(condicion_tipo_id),
	FOREIGN KEY (producto_id) REFERENCES Producto(producto_id)
)
GO
CREATE TABLE Servicio
(
	servicio_id INT NOT NULL PRIMARY KEY IDENTITY,
	cliente_id INT NOT NULL,
	producto_id INT NOT NULL,
	fecha_registro DATETIME NOT NULL,
	FOREIGN KEY (cliente_id) REFERENCES Cliente(cliente_id),
	FOREIGN KEY (producto_id) REFERENCES Producto(producto_id)
)
GO
INSERT INTO Pais(NOMBRE) VALUES ('Panamá');
INSERT INTO Pais(NOMBRE) VALUES ('México');
INSERT INTO Pais(NOMBRE) VALUES ('Colombia');
GO
INSERT INTO Cliente (CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION, INGRESOS, PAIS_ID)
VALUES ('00000001', 'López', 'Arias', '1980-09-13', 'Alberto', 'M', 'El Carmen', 1800, 1);
INSERT INTO Cliente (CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION, INGRESOS, PAIS_ID)
VALUES ('00000002', NULL, 'Ramírez', '2006-09-13', 'María', 'F', 'San francisco', 600, 2);
INSERT INTO Cliente (CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION, INGRESOS, PAIS_ID)
VALUES ('00000003', 'Pimentel', 'Trujillo', '1973-09-13', 'Lourdes', 'F', 'Obarrio', 4600, 3);
GO
INSERT INTO Categoria (NOMBRE) VALUES ('Ahorro');
INSERT INTO Categoria (nombre) VALUES ('Inversión');
INSERT INTO Categoria (nombre) VALUES ('Financiación');
INSERT INTO Categoria (nombre) VALUES ('Otros');
GO
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0001', '2021-01-31', 'Cuentas', 1);
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0002', '2021-01-31', 'Tarjeta debito', 3);
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0003', '2021-01-31', 'Tarjeta crédito', 3);
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0004', '2021-01-31', 'Seguro', 4);
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0005', '2021-01-31', 'Inversiones', 2);
INSERT INTO PRODUCTO (CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES ('0006', '2021-01-31', 'Giros', 4);
GO
INSERT INTO CondicionTipo VALUES ('EDAD MINIMA')
INSERT INTO CondicionTipo VALUES ('INGRESO MINIMO')
INSERT INTO CondicionTipo VALUES ('RESIDENCIA')
GO
INSERT INTO Condicion VALUES (1, 1, 18)   --CUENTAS MAYOR 18
INSERT INTO Condicion VALUES (3, 1, 1)    --CUENTAS RECIDENCIA PANAMA 
INSERT INTO Condicion VALUES (1, 2, 18)   --TD MAYOR 18
INSERT INTO Condicion VALUES (2, 2, 500)  --TD INGRESO > 500
INSERT INTO Condicion VALUES (3, 2, 1)    --TD RECIDENCIA PANAMA > 500
INSERT INTO Condicion VALUES (1, 3, 20)   --TC MAYOR 20
INSERT INTO Condicion VALUES (2, 3, 1500) --TC INGRESO > 1500
INSERT INTO Condicion VALUES (3, 3, 1)    --TC RECIDENCIA PANAMA
INSERT INTO Condicion VALUES (1, 4, 15)   --SEGURO MAYOR 15
INSERT INTO Condicion VALUES (2, 4, 1000) --SEGURO INGRESO > 1000
INSERT INTO Condicion VALUES (1, 5, 25)   --INVERSION MAYOR 25
INSERT INTO Condicion VALUES (2, 5, 4500) --INVERSION INGRESO > 4500
INSERT INTO Condicion VALUES (3, 6, 1)    --GIROS RECIDENCIA PANAMA
GO
INSERT INTO SERVICIO VALUES (1, 3, GETDATE())
INSERT INTO SERVICIO VALUES (1, 4, GETDATE())
INSERT INTO SERVICIO VALUES (3, 4, GETDATE())
INSERT INTO SERVICIO VALUES (3, 5, GETDATE())

GO
DECLARE @EDAD INT 
DECLARE @INGRESO DECIMAL
DECLARE @RESIDENCIA INT

SET @EDAD = 42      -- 42 -- 18
SET @INGRESO = 600  -- 600-- 1000
SET @RESIDENCIA = 1

SELECT P.* 
FROM (
SELECT ct.nombre as id, p.producto_id AS PRODUCTO_ID, sum(c.valor) AS VALOR
FROM Producto P
INNER JOIN Condicion C ON C.producto_id = P.producto_id
INNER JOIN CondicionTipo CT ON C.condicion_tipo_id = CT.condicion_tipo_id
GROUP BY p.producto_id, ct.nombre) AS C
PIVOT (SUM(VALOR)
       FOR id IN ([EDAD MINIMA], [INGRESO MINIMO], [RESIDENCIA])) AS PVT
INNER JOIN Producto P ON P.producto_id = PVT.PRODUCTO_ID
WHERE (@RESIDENCIA =RESIDENCIA AND [EDAD MINIMA] IS NULL AND [INGRESO MINIMO] IS NULL) OR
(@EDAD >= [EDAD MINIMA] AND [INGRESO MINIMO] IS NULL AND @RESIDENCIA = RESIDENCIA) OR
(@EDAD >= [EDAD MINIMA] AND @INGRESO >= [INGRESO MINIMO] AND RESIDENCIA IS NULL) OR
(@RESIDENCIA = RESIDENCIA AND @EDAD >= [EDAD MINIMA] AND @INGRESO >= [INGRESO MINIMO]) 