INSERT INTO Categoria (NOMBRE) VALUES ('Ahorro');
INSERT INTO Categoria (nombre) VALUES ('Inversión');
INSERT INTO Categoria (nombre) VALUES ('Financiación');
INSERT INTO Categoria (nombre) VALUES ('Otros');

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (1L, '0001', '2021-01-31', 'Cuentas', 1L);

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (2L, '0002', '2021-01-31', 'Tarjeta debito', 3L);

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (3L, '0003', '2021-01-31', 'Tarjeta crédito', 3L);

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (4L, '0004', '2021-01-31', 'Seguro', 4L);

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (5L, '0005', '2021-01-31', 'Inversiones', 2L);

INSERT INTO PRODUCTO (PRODUCTO_ID, CODIGO, FECHA_REGISTRO, DESCRIPCION, CATEGORIA_ID)
VALUES (6L, '0006', '2021-01-31', 'Giros', 4L);

INSERT INTO Cliente (CLIENTE_ID, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE)
VALUES (1, 'Piedras', 'Pica', '1980-09-13', 'Pedro')