INSERT INTO PAIS (NOMBRE) VALUES ('Panamá');
INSERT INTO PAIS (NOMBRE) VALUES ('México');
INSERT INTO PAIS (NOMBRE) VALUES ('Colombia');
INSERT INTO PAIS (NOMBRE) VALUES ('Estados Unidos');
INSERT INTO PAIS (NOMBRE) VALUES ('Canada');
INSERT INTO PAIS (NOMBRE) VALUES ('Peru');
INSERT INTO PAIS (NOMBRE) VALUES ('Venezuela');

INSERT INTO Cliente (CLIENTE_ID, CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,  SEXO, FECHA_NACIMIENTO, INGRESO, DIRECCION, PAIS_ID)
VALUES (1L, '00000001', 'Ana Teresa', 'López', 'Arias', 'M', '1980-09-13', 600, 'El Carmen', 1L);

INSERT INTO Cliente (CLIENTE_ID, CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,  SEXO, FECHA_NACIMIENTO, INGRESO, DIRECCION, PAIS_ID)
VALUES (2L, '00000002', 'María', 'Arauz', 'Pérez', 'F', '1960-01-07', 4800, 'El Ingenio', 1L);

INSERT INTO Cliente (CLIENTE_ID, CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,  SEXO, FECHA_NACIMIENTO, INGRESO, DIRECCION, PAIS_ID)
VALUES (3L, '00000003', 'Javier', 'Hernandez', null, 'M', '1965-09-28', 2300, 'Avenida primavera', 2L);

INSERT INTO Cliente (CLIENTE_ID, CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,  SEXO, FECHA_NACIMIENTO, INGRESO, DIRECCION, PAIS_ID)
VALUES (4L, '00000004', 'Rodrigo', 'Henao', 'Montoya', 'M', '1975-06-21', 1200, 'Avenida de lo caidos', 3L);

INSERT INTO Cliente (CLIENTE_ID, CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,  SEXO, FECHA_NACIMIENTO, INGRESO, DIRECCION, PAIS_ID)
VALUES (5L, '00000005', 'Gabriela', 'Pacheco', 'Arias', 'F', '1980-09-13', 2500, 'San francisco', 1L);
