INSERT INTO Cliente (CLIENTE_ID, CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION)
VALUES (1L, '00000001', 'López', 'Arias', '1980-09-13', 'Alberto', 'M', 'El Carmen');

INSERT INTO Cliente (CLIENTE_ID, CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION)
VALUES (2L, '00000002', null, 'Ramírez', '1976-02-09', 'María', 'F', 'San francisco');

INSERT INTO Cliente (CLIENTE_ID, CEDULA, APELLIDO_MATERNO, APELLIDO_PATERNO, FECHA_NACIMIENTO, NOMBRE, SEXO, DIRECCION)
VALUES (3L, '00000003', 'Pimentel', 'Trujillo', '1990-12-01', 'Lourdes', 'F', 'Obarrio');