server:
  port: 8089 
spring:
  cloud:
    config:
      server:
        git:
          password: =${GIT_PASSWORD}
          search-paths: config-services
          #searchPaths: config-services
          uri: https://github.com/cesarpb80/testproject.git
          #uri: file://projectsrepository/config-services/
          username: ${GIT_USERNAME}
  security:
    user:
      name: root
      password: p4sw0rd