eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: 
            - GET
            - POST
            - DELETE
            - PUT          